#!/bin/bash

if [ -z "$1" ]
then
    echo "Error: No commit message provided."
    exit 1
fi

# Check if the current directory is inside a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1
then
    echo "Error: Not a git repository. Please run 'git init' to set up the repository."
    exit 1
fi
# Get the current branch name
current_branch=$(git rev-parse --abbrev-ref HEAD)
# Check if there are changes to commit
if ! git diff-index --quiet HEAD --
then
    # Run git add -A
    git add -A

    # Run git commit with the provided commit message
    git commit -m "$1"
else
    # If there are no changes to commit, print a message and exit
    echo "No changes to commit."
    exit 0
fi

# Push to the current branch
git push origin "$current_branch"

#TODO: add a functionality that if there is data to push but nothing to commit, it will push what it has instead of exiting